### PR TITLE
Provisioning section and fix label

### PR DESCRIPTION
**Pull request by fabbri-marco**
Add provisioning section and fix label

### CODE REVIEW

**Comment by gsanchietti** [comment]
Please fix all broken links.

**Comment by fabbri-marco** [comment]
fixed links:
- wizard-configurations
- wizard-section
-  provisioning-scopes-priority

nethvoice-mobile, wizard-multiple-phones are still broken because the manual section must be added

**Comment by fabbri-marco** [comment]
Add applications section and delete broken links.

**Review by gsanchietti — CHANGES_REQUESTED** [review]
Please fix:
```
nethvoice.rst:157: WARNING: undefined label: wizard-configurations
nethvoice.rst:352: WARNING: undefined label: wizard-configuration
nethvoice.rst:1137: WARNING: Bullet list ends without a blank line; unexpected unindent.
```

**Review by gsanchietti — APPROVED** [review]
Syntax is correct, there is only a link in italiana (fisici) that can be fixed later.

**Review by andrea-marchionni — APPROVED** [review]

**Pull request merged**
